### ISSUE TITLE
Detailansicht

### ISSUE THREAD

**Issue by LucHauser** [LucHauser/ThunderBoost#12]
## Story
Als Besucher möchte ich die Boosterdrinks in der Detailansicht ansehen und mich informieren

## Akzeptanzkriterium
Bei Klick auf das Produkt soll der Benutzer anschliessend auf der Einzeldetailseite des Produktes ankommen.
In der Detailansicht sollen Informationen wie Zuckergehalt, Coffein-Gehalt, Anzahl Portionen und eine Beschreibung enthalten.

## DoD

- [ ] Alle Akzeptanzkriterien erfüllt
- [ ] Funktionale Tests erfüllt
- [ ] Keine bekannte Mängel, keine Bugs
- [ ] Peer-Code-Review bestanden
- [ ] Dokumentation vollständig
- [ ] Implementiert nach Mockup

**Comment by nilxxi** [comment]
Test vollständig
