### ISSUE TITLE
Warenkorb

### ISSUE THREAD

**Issue by LucHauser** [LucHauser/ThunderBoost#13]
##Story
Als Benutzer möchte ich die Produkte in den Warenkorb schieben, um später checkouten zu können

## Akzeptanzkriterium
In der Navigationsleiste soll auf der Rechte Seite ein Icon von einem Einkaufswagen dargestellt werden. Beim Einfügen der Produkte, soll die Navigationsleiste eine Zahl darstellen, wieviel Produkte im Warenkorb sind

## DoD

- [x] Alle Akzeptanzkriterien erfüllt
- [x] Funktionale Tests erfüllt
- [x] Keine bekannte Mängel, keine Bugs
- [x] Peer-Code-Review bestanden
- [x] Dokumentation vollständig
- [x] Implementiert nach Mockup

**Comment by nilxxi** [comment]
Einfügen nur via Detailansicht möglich andere nicht implementiert, checkout nicht implementiert
