### ISSUE TITLE
Informationen zu Thunderboost

### ISSUE THREAD

**Issue by LucHauser** [LucHauser/ThunderBoost#15]
## Story
Als Besucher möchte ich herausfinden, was Thunderbooster für ein Unternehmen ist.

## Akzeptanzkriterium
Auf der About-Page sollen wichtige Informationen des Unternehmens angezeigt werden. Von der Navigationsleiste soll der Benutzer mit einem Klick auf die About-Page navigieren.

## DoD

- [x] Alle Akzeptanzkriterien erfüllt
- [x] Funktionale Tests erfüllt
- [x] Keine bekannte Mängel, keine Bugs
- [x] Peer-Code-Review bestanden
- [x] Dokumentation vollständig
- [x] Implementiert nach Mockup
- [x] Information der Unternehmen verständlich

**Comment by nilxxi** [comment]
DoD vollständig, wird abschlossen
